### ISSUE TITLE
Compilation error when a unicode non-breaking space is in less file.

### ISSUE THREAD

**Issue by FrankWalinga** [SomMeri/less4j#274]
My less file won't compile when there's a unicode non-breaking space (U+00A0) somewhere.

Example:
This won't work (the nbsp is between the semicolon and the hashtag):
`@MyColour: #ff6933;`
But this will:
`@MyColour: #ff6933;`

This doesn't occur when you reference a different variable, like:
`@MyColour: @OtherColour;`

**Comment by gdelhumeau** [comment]
Hi. I have hit a similar issue:

```
.myClass { // with a non-breaking space just before "{"
  .myOtherClass {
    color: red;
  }
}
```
It compiles to:
```
.myClass  .myOtherClass {
  color: red;
}
```
which is not interpreted by both Chrome and Firefox.

With less.js, it compiles to:
```
.myClass .myOtherClass {
  color: red;
}
```
which works.

I believe using a non-breaking space was not intended in the first place, but because it worked with less.js, we haven't noticed it. I have fixed it in my project by putting a regular space instead. But I think it is still important to report it since it is a difference between less4j and less.js

**Comment by SomMeri** [comment]
This comment fails too: `//nbsp:| |`

**Comment by SomMeri** [comment]
Fixed, it will be available in the next release. If it still does not work as expected after that, let me know. New release should be available by the end of this week, if you need it faster leave the comment.
