### ISSUE TITLE
LESS level supported by less4j 1.9.0 and 1.10.0

### ISSUE THREAD

**Issue by ktngo** [SomMeri/less4j#280]
Hi SomMeri,

Do you know which level of LESS (e.g., 2.5.0?) that less4j 1.9.0 and 1.10.0 support?  Is there any wiki page showing the LESS level supported by each release of less4j?

Thanks in advance
Kam

**Comment by SomMeri** [comment]
Hi, current version 1.10.0 should support all less.js features from last release except strict-math option.  I do not have page that would show mapping, because Less4j releases did not mirrored less.js releases. Features were added in different order. 

Every less.js feature that is not implemented yet should have an [open issue](https://github.com/SomMeri/less4j/issues). If you tried latest less4j and it missed some less.js feature, please let me know.
