### ISSUE TITLE
Less4js is unable do compile code that less.js can

### ISSUE THREAD

**Issue by diorcety** [SomMeri/less4j#307]
I'am using Jawr, which used to depend on less.js until a recent version. I'm trying to migrate to the last version which uses less4j. I fall on a issue with the following code

    .flex(@display:flex) {
        display: @display;
        display:-ms-@display;
    }

```
[INFO] ERROR 85:5 no viable alternative at input 'display' in abstract mixin or namespace (which started at 83:1)
[INFO]  84:     display: @display;
[INFO]  85:     display:-ms-@display;
[INFO]  86: }
[INFO] 
[INFO] ERROR 85:5 no viable alternative at input 'display' in ruleset (which started at 85:5)
[INFO]  84:     display: @display;
[INFO]  85:     display:-ms-@display;
[INFO]  86: }
```

**Comment by SomMeri** [comment]
It seems that issue was fixed in the meantime. Both latest master compile and [less.js 2.5.3 compile it](http://lesscss.org/less-preview/#%7B%22less%22%3A%22.flex(%40display%3Aflex)%20%7B%5Cn%20%20%20%20display%3A%20%40display%3B%5Cn%20%20%20%20display%3A-ms-%40display%3B%5Cn%7D%5Cndiv%20%7B%5Cn%20%20.flex()%3B%5Cn%7D%22%7D) to
````
div {
  display: flex;
  display: -ms- flex;
}
```` 

I will do new release later this week or monday. If it still does not work after that for you, let me know.

Side note: both have space between `-ms-` and `flex`. If it is not intentional use this: `display: ~"-ms-@{display}";` - it produces `-ms-flex` without space in both less.js and less4j.
